/// Flutter icons CardsIcon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CardsIcon
///      fonts:
///       - asset: fonts/CardsIcon.ttf
///
///
///
import 'package:flutter/widgets.dart';

// https://qiita.com/tomoDev_/items/79ac1391d4e3d9c9eec1
class CardsIcon {
  CardsIcon._();

  static const _kFontFam = 'CardsIcon';
  static const String? _kFontPkg = null;

  static const IconData diamond =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData club =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spade =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
